jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Login\UsuarioBundle\Entity\User: plaintext
        Login\UsuarioBundle\Entity\Admin: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuario:
            entity: { class: Login\UsuarioBundle\Entity\User, property: login }

    firewalls:
        user:
            pattern: ^/usuario
            provider: usuario
            anonymous:  ~
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /usuario/
            logout:
                path: /usuario/logout
                
        
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
