usuario_login:
    pattern: /login
    defaults: { _controller: UsuarioBundle:Default:login }

usuario_login_check:
    pattern: /login_check

usuario_logout:
    pattern: /logout
    
page_usuario:
  pattern: /
  defaults: { _controller: UsuarioBundle:Default:usuario }
 